### ISSUE TITLE
workflow or state machine ?

### ISSUE THREAD

**Issue by Diaskhan** [alexandrvslv/datawf#2]
Alexandr Could describe how U define workflows?

It is a fully workflow or state machine ?

**Comment by alexandrvslv** [comment]
Sorry for miss your's question. 
Word "workflow" used in term of providing information to user by developer, thro's the database - orm - [service] - UI and vice versa.
But in one module "Flow" class Documents have DocumentWorks entity with 1:M relation, which define it's current state(with details about date, user, permission's and etc).

**Comment by Diaskhan** [comment]
could describe simple worflow ???? configuration ???

**Comment by Diaskhan** [comment]
Параллельное выполнение ? подпроцессы, скрипт задачи ?

**Comment by alexandrvslv** [comment]
Параллельно:
```
document.Send(
    from: document.CurrentWork, 
    stage:  document.CurrentWork.Stage.NextStage,
    staff: department.GetUsers()
 )
```
Скрипты:
`new StagePropcedure(Id = 1, StageId = 1, ProcedureType.Start, Procedure = Schema.Procedures["DocumentNumberGenerator"]);`

**Comment by alexandrvslv** [comment]
Название не благозвучное)

**Comment by Diaskhan** [comment]
Возвращение к предыдущей стадии в случае шлюза ? 

Просто есть же bpel и bpmn ?

**Comment by alexandrvslv** [comment]
Возвращаясь к первому ответу, это просто набор библиотек, при желании можно реализовать парсинг bpel одной дополнительной "либой"

**Comment by alexandrvslv** [comment]
StageProcedure ссылается на название класса, с учетом CI/CD отказался от хранения скриптов отдельно, все в исходники)
```
public class DocumentNumberGenerator : IExecutable
    {
        public virtual long GenerateIdentifier(string name)
        {
            var sequence = Document.DBTable.Schema.Sequences[name];
            if (sequence == null)
            {
                sequence = new DBSequence(name) { };
                Document.DBTable.Schema.Sequences.Add(sequence);
                try { DBService.CommitChanges(); }
                catch (Exception ex)
                {
                    Helper.OnException(ex);
                    DBService.Changes.Clear();
                }
                DBService.Save();
            }
           return sequence.Next();
        }

        public virtual string Generate(Template template)
        {
            return template.Code + GenerateIdentifier("template_" + template.Id).ToString("D8");
        }

        public object Execute(ExecuteArgs arg)
        {
            var darg = (DocumentExecuteArgs)arg;
            var document = (Document)arg.Document;
            if (string.IsNullOrEmpty(document.Number))
            {
                document.Number = Generate(document.Template);
            }
            return null;
        }
    }
```

**Comment by Diaskhan** [comment]
Ты видел Elma-comunity ?
Посмотри должно понравиться ))
